//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtectAnimal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.works = new HashSet<works>();
        }
    
        public int Uid { get; set; }

        [Display(Name="昵称")]
        [Required,StringLength(10,MinimumLength =2,ErrorMessage ="字符长度为2-10")]
        public string Name { get; set; }

        [Display(Name="邮箱")]
       [Required(ErrorMessage ="请填写邮箱")]
       [EmailAddress(ErrorMessage ="请填写有效邮箱")]
        public string Email { get; set; }

        [Display(Name ="密码")]
        [Required(ErrorMessage ="请填写密码"), StringLength(20, MinimumLength = 6,ErrorMessage ="密码长度为6~20个字符")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<works> works { get; set; }
    }
}
