//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtectAnimal
{
    using System;
    using System.Collections.Generic;
    
    public partial class works
    {
        public int Wid { get; set; }
        public int Uid { get; set; }
        public int Flag { get; set; }
        public string Context { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string CoreSentence { get; set; }
    
        public virtual user user { get; set; }
    }
}
